# -*- coding: utf-8 -*-
"""
Generator for tokyo.ics — the single source of truth for the Tokyo calendar.
Edit an event below and re-run:  python scripts/gen_tokyo_ics.py
It writes ../tokyo.ics and prints validation counts. Uses scripts/ics_common.py.

Keep this in sync with Tokyo_Itinerary_Plan.md (and the HTML Tokyo tab) — see CLAUDE.md.
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from ics_common import maps, write_calendar  # noqa: E402

# (day, evt, date, start, end, summary, location, [desc lines])
EVENTS = [
    # DAY 1 — Thu 12 Nov
    (1, 1, "20261112", "163000", "173000",
     "Arrive Tokyo — Shinkansen from Kyoto, drop bags",
     "2-Chome-2-11 Kabukicho, Shinjuku City, Tokyo 160-0021",
     ["~2h15 Nozomi Kyoto -> Tokyo Station, then ~15 min to Shinjuku (JR Chuo Rapid or Yamanote).",
      "Drop bags at the apartment (booked, provisional - address not yet re-verified against a live listing).",
      "Then an orientation walk through Kabukicho past the Godzilla head.",
      "Map: " + maps("Shinjuku Station Tokyo")]),
    (1, 2, "20261112", "190000", "210000",
     "Dinner: Omoide Yokocho",
     "1 Chome Nishishinjuku, Shinjuku City, Tokyo",
     ["Specialty: charcoal yakitori & grilled offal at tiny standing/counter stalls.",
      "Lantern-lit alley 5 min from Shinjuku West Exit. No reservations - walk the lane and grab stools.",
      "Map: " + maps("Omoide Yokocho Shinjuku")]),
    (1, 3, "20261112", "210000", "230000",
     "OPTIONAL: Golden Gai (start at Albatross)",
     "1 Chome Kabukicho, Shinjuku City, Tokyo",
     ["~200 micro-bars across six alleys; liveliest after 20:00.",
      "Albatross: 3 floors, chandelier-lit, foreigner-friendly, ¥500 cover with a snack - good first-night pick.",
      "Map: " + maps("Golden Gai Shinjuku")]),

    # DAY 2 — Fri 13 Nov
    (2, 1, "20261113", "083000", "100000",
     "Meiji Jingu",
     "1-1 Yoyogikamizonocho, Shibuya City, Tokyo 151-8557",
     ["Free. Opens at sunrise (~06:20 in Nov), closes ~16:20.",
      "Tokyo's grandest shrine in a forest of 100,000 donated trees. Go early for empty gravel approaches.",
      "Route: Shinjuku -> Harajuku, 2 stops / ~4 min on the Yamanote.",
      "Map: " + maps("Meiji Jingu Tokyo")]),
    (2, 2, "20261113", "100000", "113000",
     "Takeshita-dori + Cat Street (Harajuku)",
     "Takeshita St, Jingumae, Shibuya City, Tokyo",
     ["Takeshita's teen-fashion gauntlet, then the calmer Ura-Harajuku back lanes for streetwear & vintage.",
      "Map: " + maps("Takeshita Street Harajuku")]),
    (2, 3, "20261113", "113000", "123000",
     "Lunch: Fuunji (tsukemen)",
     "2-14-3 Yoyogi, Shibuya City, Tokyo 151-0053",
     ["Specialty: chicken-and-niboshi (dried sardine) tsukemen. Large noodle size free.",
      "Among Tokyo's best tsukemen; huge queue by noon - arrive before 11:00 or after 14:00. Cash-friendly, tiny counter.",
      "Map: " + maps("Fuunji Tokyo tsukemen")]),
    (2, 4, "20261113", "133000", "160000",
     "Shibuya Scramble + Hachiko + Shibuya Sky",
     "Shibuya Scramble Square, 2-24-12 Shibuya, Shibuya City, Tokyo",
     ["Shibuya Sky rooftop (229 m): ¥2,700 before 15:00 / ¥3,400 from 15:00. Open 10:00-22:30, last entry 21:20.",
      "BOOK a ~15:30-16:00 timed slot for daylight -> sunset -> city lights. Slots sell out.",
      "Map: " + maps("Shibuya Sky Scramble Square")]),
    (2, 5, "20261113", "190000", "210000",
     "Dinner: Nonbei Yokocho",
     "1 Chome Shibuya, Shibuya City, Tokyo",
     ["Tiny two-storey bars & yakitori counters beside the Shibuya train tracks - a smaller, local Golden Gai.",
      "Map: " + maps("Nonbei Yokocho Shibuya")]),
    (2, 6, "20261113", "210000", "230000",
     "OPTIONAL: The SG Club",
     "1-7-8 Jinnan, Shibuya City, Tokyo 150-0041",
     ["Shingo Gokan bar; 9 consecutive years on Asia's 50 Best Bars.",
      "Casual 'Guzzle' upstairs is walk-in friendly; 'Sip' speakeasy below is dressier. ~10-15 min walk from Shibuya Station.",
      "Map: " + maps("The SG Club Shibuya")]),

    # DAY 3 — Sat 14 Nov
    (3, 1, "20261114", "080000", "100000",
     "Tsukiji Outer Market",
     "4 Chome Tsukiji, Chuo City, Tokyo 104-0045",
     ["Specialty: tamagoyaki, uni, grilled seafood skewers, standing sushi. 460+ stalls.",
      "Best window 08:00-10:00 - half the top stalls sell out by ~11:00. Closed Sundays & scattered Weds (Sat is safe).",
      "Graze across several stalls rather than one sit-down meal.",
      "Map: " + maps("Tsukiji Outer Market Tokyo")]),
    (3, 2, "20261114", "103000", "123000",
     "Ginza — flagship stores",
     "Ginza, Chuo City, Tokyo",
     ["~15-min walk from Tsukiji. Ginza Six, the Uniqlo & Muji flagships (Muji has a bakery), Itoya stationery megastore.",
      "Optional: Imperial Palace East Gardens (free; open Sat - closed Mon & Fri), ~10 min from Tokyo Station.",
      "Map: " + maps("Ginza Tokyo")]),
    (3, 3, "20261114", "130000", "143000",
     "Tokyo Station Marunouchi",
     "1 Chome Marunouchi, Chiyoda City, Tokyo",
     ["Photograph the restored 1914 red-brick facade, then the basement Character Street / Ramen Street if peckish.",
      "Map: " + maps("Tokyo Station Marunouchi")]),
    (3, 4, "20261114", "190000", "210000",
     "Cocktails: Bar High Five (Ginza)",
     "Efu Bldg B1F, 7-2-14 Ginza, Chuo City, Tokyo 104-0061",
     ["Specialty: bartender's-choice omakase cocktails, no printed menu - legendary bartender Hidetsugu Ueno.",
      "Intimate & world-renowned. RESERVATION ADVISED; cover charge; dress smart-ish. Do an early casual bite first.",
      "Map: " + maps("Bar High Five Ginza")]),

    # DAY 4 — Sun 15 Nov (heavy walking)
    (4, 1, "20261115", "083000", "103000",
     "Senso-ji + Nakamise-dori",
     "2-3-1 Asakusa, Taito City, Tokyo 111-0032",
     ["Free; grounds 24h, main hall 06:30-17:00. Enter via the Kaminarimon giant lantern.",
      "Go before 10:00 to beat the crush. HEAVY-WALKING DAY today (Asakusa + Ameyoko + Akihabara).",
      "Map: " + maps("Senso-ji Asakusa")]),
    (4, 2, "20261115", "110000", "120000",
     "Lunch: Onigiri Asakusa Yadoroku",
     "3-9-10 Asakusa, Taito City, Tokyo 111-0032",
     ["Specialty: hand-formed onigiri. Tokyo's oldest onigiri specialist (since 1954), Michelin Bib Gourmand.",
      "Tiny counter, limited hours, can sell out - arrive early. Alt: Asakusa Imahan for century-old sukiyaki.",
      "Map: " + maps("Onigiri Asakusa Yadoroku")]),
    (4, 3, "20261115", "130000", "150000",
     "Ueno — Park museums or Ameyoko",
     "Ueno Park / Ameyoko, Taito City, Tokyo",
     ["Choose a lane: Tokyo National Museum (closed Mon; open Sun), or the Ameyoko market street under the JR tracks.",
      "Route: Asakusa -> Ueno ~5 min (Ginza Line); Ueno -> Akihabara 3 min (Yamanote).",
      "Map: " + maps("Ameyoko Ueno")]),
    (4, 4, "20261115", "153000", "180000",
     "Akihabara — Electric Town",
     "Akihabara, Chiyoda/Taito City, Tokyo",
     ["Multi-floor arcades (GiGO, Taito Station), retro games at Super Potato, anime/figures on Chuo-dori.",
      "Chuo-dori is car-free Sun 13:00-17:00 (Oct-Mar). Kanda Myojin shrine is a 7-min walk uphill.",
      "Map: " + maps("Akihabara Electric Town")]),
    (4, 5, "20261115", "193000", "213000",
     "Dinner: Ebisu Yokocho",
     "1-7-4 Ebisu, Shibuya City, Tokyo 150-0013",
     ["Specialty: 20+ independent izakaya in one indoor alley - yakitori, oden, fresh fish, wine.",
      "Rowdy, group-friendly, ~¥2,000+/head, no bookings. ~2 min from Ebisu Station East Exit; easy loop home.",
      "Map: " + maps("Ebisu Yokocho")]),

    # DAY 5 — Mon 16 Nov (Hakone day trip)
    (5, 1, "20261116", "073000", "090000",
     "Odakyu Romancecar: Shinjuku -> Hakone-Yumoto",
     "Odakyu Shinjuku Station, Tokyo",
     ["Direct limited express, ~85 min. RESERVE seats (right side C/D for Mt Fuji).",
      "Buy the Hakone Freepass digitally (EMot app / Klook) to skip the morning queue - it covers the whole loop.",
      "Map: " + maps("Odakyu Shinjuku Station")]),
    (5, 2, "20261116", "093000", "160000",
     "Hakone loop: Gora / Owakudani / Lake Ashi",
     "Hakone, Kanagawa",
     ["Mountain railway to Gora -> cablecar to Sounzan -> ropeway over Owakudani (black eggs) -> pirate ship across Lake Ashi to Moto-Hakone (lake torii).",
      "Peak autumn foliage in November. Lunch on the loop: soba around Gora/Yumoto or the Owakudani black eggs.",
      "Backup if ropeway is wind/gas-closed: substitute buses + Hakone Open-Air Museum (all-weather).",
      "Map: " + maps("Owakudani Hakone")]),
    (5, 3, "20261116", "160000", "173000",
     "Onsen: Hakone Yuryo",
     "4 Tonosawa, Hakone, Ashigarashimo District, Kanagawa 250-0315",
     ["Near Hakone-Yumoto. Private-rental baths good for a group - sidesteps the no-visible-tattoos rule of public baths.",
      "Map: " + maps("Hakone Yuryo onsen")]),
    (5, 4, "20261116", "173000", "190000",
     "Romancecar back to Shinjuku",
     "Hakone-Yumoto Station, Kanagawa",
     ["~85 min back to Shinjuku. Easy dinner near home after.",
      "Map: " + maps("Hakone-Yumoto Station")]),

    # DAY 6 — Tue 17 Nov
    (6, 1, "20261117", "103000", "133000",
     "Shimokitazawa",
     "Kitazawa, Setagaya City, Tokyo",
     ["7 min from Shinjuku (Odakyu / Keio Inokashira). Tokyo's indie/vintage capital - no chain stores on the main lanes.",
      "Chicago, Flamingo, New York Joe Exchange (vintage inside a former bathhouse). Graze cafés/curry for lunch.",
      "Map: " + maps("Shimokitazawa Tokyo")]),
    (6, 2, "20261117", "143000", "173000",
     "Nakameguro",
     "Nakameguro, Meguro City, Tokyo",
     ["The cool-but-calmer canal neighbourhood. Meguro River promenade, design shops/galleries.",
      "Multi-floor Starbucks Reserve Roastery flagship on the river.",
      "Map: " + maps("Nakameguro Tokyo")]),
    (6, 3, "20261117", "190000", "210000",
     "Dinner + drinks: Nakameguro / Golden Gai",
     "Nakameguro / Shinjuku, Tokyo",
     ["Nakameguro riverside izakaya & yakitori, then optionally back toward Shibuya - or a proper Golden Gai round.",
      "Golden Gai English-friendly picks: Bar Plastic Model, Cambiare.",
      "Map: " + maps("Nakameguro izakaya")]),

    # DAY 7 — Wed 18 Nov
    (7, 1, "20261118", "093000", "103000",
     "Tokyo Metropolitan Gov Building (free decks)",
     "2-8-1 Nishishinjuku, Shinjuku City, Tokyo 163-8001",
     ["Nishi-Shinjuku, 202 m, FREE - a no-cost rival to the paid towers.",
      "Nightly 'Tokyo Night & Light' projection show on the facade if you return after dark.",
      "Map: " + maps("Tokyo Metropolitan Government Building")]),
    (7, 2, "20261118", "110000", "130000",
     "Shinjuku Gyoen",
     "11 Naitomachi, Shinjuku City, Tokyo 160-0014",
     ["¥500. CLOSED Mondays - open today (Wed). Japanese/English/French garden sections.",
      "Autumn foliage in mid-to-late November. ~10 min from the apartment.",
      "Map: " + maps("Shinjuku Gyoen National Garden")]),
    (7, 3, "20261118", "130000", "140000",
     "Lunch: Ichiran Kabukicho (ramen)",
     "1-22-7 Kabukicho, Shinjuku City, Tokyo",
     ["Solo-booth tonkotsu; accepts cards/IC/PayPay. Some branches open late/24h.",
      "Or any Shinjuku West-Exit ramen shop.",
      "Map: " + maps("Ichiran Kabukicho Shinjuku")]),
    (7, 4, "20261118", "190000", "230000",
     "Cocktail crawl: Zoetrope / Benfiddich / New York Bar",
     "Nishi-Shinjuku, Shinjuku City, Tokyo",
     ["All three are SUNDAY-CLOSED, so a Wednesday works. Benfiddich & Zoetrope are tiny (9-15 seats) - arrive at opening.",
      "Bar Zoetrope: 300+ Japanese whiskies, from 17:00. 7-10-14 Nishishinjuku.",
      "Bar Benfiddich: foraged-botanical cocktails, 9 seats, from 18:00. 1-13-7 Nishishinjuku.",
      "Optional: New York Bar, Park Hyatt 52F - cover after 20:00, smart dress.",
      "Map: " + maps("Bar Benfiddich Nishi-Shinjuku")]),

    # DAY 8 — Thu 19 Nov
    (8, 1, "20261119", "100000", "120000",
     "teamLab Planets TOKYO (booked slot)",
     "6-1-16 Toyosu, Koto City, Tokyo 135-0061",
     ["Barefoot, wade-through digital-art rooms. Open 08:30-22:00, last entry 60 min before close.",
      "TIMED tickets from ¥3,800, on sale ~late-Aug for Nov and SELL OUT - book first. You get wet to the knee: bring shorts/roll-ups.",
      "~10 min from Shin-Toyosu on the Yurikamome.",
      "Map: " + maps("teamLab Planets Toyosu Tokyo")]),
    (8, 2, "20261119", "123000", "153000",
     "Toyosu Market or Odaiba waterfront",
     "Toyosu / Odaiba, Koto City, Tokyo",
     ["Toyosu Market (tuna-auction viewing decks + fresh sushi) is a short walk, or Yurikamome to Odaiba.",
      "Odaiba: Unicorn Gundam statue at DiverCity, Rainbow Bridge views, Odaiba Seaside Park.",
      "Map: " + maps("Odaiba Tokyo")]),
    (8, 3, "20261119", "190000", "230000",
     "Final big night — Kabukicho",
     "Kabukicho, Shinjuku City, Tokyo",
     ["Last night all three together. Yakiniku/izakaya group dinner, a Golden Gai farewell round, karaoke (Karaoke Kan / Big Echo) or a Kabukicho club.",
      "Map: " + maps("Kabukicho Shinjuku")]),

    # DAY 9 — Fri 20 Nov
    (9, 1, "20261120", "100000", "110000",
     "Jai -> Haneda (13:15 flight -> London Heathrow)",
     "Shinjuku Station, Tokyo",
     ["Leave Shinjuku by ~10:00 - Toei/Keikyu via Shinagawa or the Airport Limousine bus from Shinjuku (~45-75 min).",
      "Sort checkout/bags the night before so the morning is clean.",
      "Map: " + maps("Haneda Airport Tokyo")]),
    (9, 2, "20261120", "113000", "160000",
     "Mandeep & Tom: Yanaka old town OR Kamakura",
     "Yanaka (Nippori) / Kamakura",
     ["Option A - Yanaka/Yanesen old town: Nippori -> Yanaka Ginza street food -> Nezu Shrine red-torii corridor -> Sendagi. Low-key half-day, mostly walking.",
      "Option B - Kamakura day trip: JR Yokosuka Line ~1 hr, ~¥920; Great Buddha at Kotoku-in (enter for ¥50) + Hase-dera. Only if legs are fresh after Hakone.",
      "Map A: " + maps("Yanaka Ginza Tokyo"),
      "Map B: " + maps("Kotoku-in Great Buddha Kamakura")]),
    (9, 3, "20261120", "190000", "210000",
     "Last night as a pair",
     "Kabukicho, Shinjuku City, Tokyo",
     ["An easy Kabukicho izakaya + a final Golden Gai round.",
      "Map: " + maps("Golden Gai Shinjuku")]),

    # DAY 10 — Sat 21 Nov
    (10, 1, "20261121", "100000", "120000",
     "Light morning + last souvenirs",
     "Kabukicho, Shinjuku City, Tokyo",
     ["Don Quijote Kabukicho (24h, 2 min from home), a final coffee/ramen, anything the week missed within Shinjuku.",
      "Map: " + maps("Don Quijote Kabukicho Shinjuku")]),
    (10, 2, "20261121", "153000", "170000",
     "Narita Express -> Narita (19:30 flight)",
     "Shinjuku Station (Narita Express), Tokyo",
     ["Mandeep & Tom: N'EX direct from Shinjuku (~80 min) or Keisei via Nippori. 19:30 flight -> Shanghai -> London Gatwick.",
      "Leave the apartment ~15:30-16:00 (~3.5 hrs before departure + the train). PRE-BOOK the N'EX seat.",
      "Map: " + maps("Narita Airport Terminal")]),
]


def main():
    events = [
        {"day": d, "evt": e, "date": dt, "start": s, "end": en,
         "summary": summ, "location": loc, "desc": desc}
        for (d, e, dt, s, en, summ, loc, desc) in EVENTS
    ]
    target = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "tokyo.ics")
    info = write_calendar(os.path.normpath(target),
                          "Tokyo Itinerary – Nov 2026", "tokyo-itinerary", events)
    print("wrote tokyo.ics:", info)


if __name__ == "__main__":
    main()
